samochody/urls.py
from django.contrib import admin
from django.urls import path
from samochody_web import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.homeView, name='homeView'),
    path('api/cars/', views.CarList.as_view(), name='car-list'),
    path('api/cars/<int:pk>/', views.CarDetail.as_view(), name='car-detail'),
]

samochody_web/models.py
from django.db import models

# Create your models here.

class Car(models.Model):
    ENGINE_CHOICES = [
        ('benzyna', 'Benzyna'),
        ('diesel', 'Diesel'),
        ('hybryda', 'Hybryda'),
        ('elektryczny', 'Elektryczny'),
    ]

    DRIVE_TRAIN_CHOICES = [
        ('przednionapęd', 'Przedni napęd'),
        ('tylnionapęd', 'Tylni napęd'),
        ('napęd4x4', 'Napęd 4x4'),
    ]

    GEAR_CHOICES = [
        ('manulany', 'Manualny'),
        ('automatyczny', 'Automatyczny'),
    ]

    brand = models.CharField(max_length=16, blank=False)
    model = models.CharField(max_length=30, blank=False)
    year = models.PositiveSmallIntegerField(blank=False)
    engineCapacity = models.IntegerField(blank=False)
    engineType = models.CharField(max_length=16, choices=ENGINE_CHOICES, blank=False)
    gear = models.CharField(max_length=16, choices=GEAR_CHOICES, blank=False)
    drive_train = models.CharField(max_length=16, choices=DRIVE_TRAIN_CHOICES, blank=False)
    doors = models.IntegerField(blank=False)

def __str__(self):
    return f" {self.brand}  {self.model}  {self.year} {self.engineCapacity} {self.engineType} {self.gear} {self.drive_train} {self.doors}"

samochody_web/views.py
from django.shortcuts import render  
from .models import Car
from rest_framework import generics
from .serializers import CarSerializer

# Create your views here. 
class CarList(generics.ListCreateAPIView):
    queryset = Car.objects.all()
    serializer_class = CarSerializer

class CarDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Car.objects.all()
    serializer_class = CarSerializer

def homeView(request):  
    cars = Car.objects.all()
    context = {'cars': cars}   
    return render(request, 'home.html', context)

templates/home.html
<!DOCTYPE html>
<html>
    <head>
    <title>Lista Samochodów</title>
    <style>
        /* Zagnieżdżony CSS */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #333;
            color: #fff;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        footer {
            text-align: center;
            padding: 10px;
            background-color: #333;
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <h1>Lista Samochodów</h1>
    </header>
    <main>
        <table>
            <thead>
                <tr>
                    <th>Marka</th>
                    <th>Model</th>
                    <th>Rok produkcji</th>
                    <th>Pojemność silnika</th>
                    <th>Rodzaj silnika</th>
                    <th>Skrzynia biegów</th>
                    <th>Napęd</th>
                    <th>Liczba drzwi</th>
                </tr>
            </thead>
            <tbody>
                {% for car in cars %}
                    <tr>
                        <td>{{ car.brand }}</td>
                        <td>{{ car.model }}</td>
                        <td>{{ car.year }}</td>
                        <td>{{ car.engineCapacity }} cm³</td>
                        <td>{{ car.get_engineType_display }}</td>
                        <td>{{ car.get_gear_display }}</td>
                        <td>{{ car.get_drive_train_display }}</td>
                        <td>{{ car.doors }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="8">Brak dostępnych samochodów.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
    <footer>
        &copy; 2023 Moja Strona
    </footer>
</body>
</html>